In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
feature = pd.read_csv('NUSW-NB15_features.csv', encoding='ISO-8859-1')
data1 = pd.read_csv('UNSW-NB15_1.csv', encoding='utf-8-sig', header=None)
data2 = pd.read_csv('UNSW-NB15_2.csv', encoding='utf-8-sig', header=None)
data3 = pd.read_csv('UNSW-NB15_3.csv', encoding='utf-8-sig', header=None)
data4 = pd.read_csv('UNSW-NB15_4.csv', encoding='utf-8-sig', header=None)

In [3]:
display(data1.head())
display(data2.head())
display(data3.head())
display(data4.head())

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,NaN,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.0,6055,149.171.126.5,54145,tcp,FIN,0.072974,4238,60788,31,...,0,13,13,6,7,1,1,2,NaN,0
1,59.166.0.0,7832,149.171.126.3,5607,tcp,FIN,0.144951,5174,91072,31,...,0,13,13,6,7,1,1,2,NaN,0
2,59.166.0.8,11397,149.171.126.6,21,tcp,FIN,0.116107,2934,3742,31,...,1,1,2,7,5,1,1,4,NaN,0
3,59.166.0.0,3804,149.171.126.3,53,udp,CON,0.000986,146,178,31,...,0,13,13,6,7,1,1,2,NaN,0
4,59.166.0.8,14339,149.171.126.6,14724,tcp,FIN,0.038480,8928,320,31,...,0,8,20,7,5,1,1,4,NaN,0

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.1,18247,149.171.126.4,7662,tcp,FIN,0.119596,4550,68342,31,...,,6,2,2,5,1,1,2,NaN,0
1,59.166.0.3,54771,149.171.126.2,27709,tcp,FIN,0.650574,8928,320,31,...,,3,5,2,4,1,1,4,NaN,0
2,59.166.0.8,13289,149.171.126.9,5190,tcp,FIN,0.007980,2158,2464,31,...,,3,5,1,1,1,1,3,NaN,0
3,149.171.126.18,1043,175.45.176.3,53,udp,INT,0.000005,264,0,60,...,,19,19,19,19,19,19,19,NaN,0
4,149.171.126.18,1043,175.45.176.3,53,udp,INT,0.000005,264,0,60,...,,19,19,19,19,19,19,19,NaN,0

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.9,7045,149.171.126.7,25,tcp,FIN,0.201886,37552,3380,31,...,,2,2,7,4,1,1,3,NaN,0
1,59.166.0.9,9685,149.171.126.2,80,tcp,FIN,5.864748,19410,1087890,31,...,,3,1,4,4,1,1,1,NaN,0
2,59.166.0.2,1421,149.171.126.4,53,udp,CON,0.001391,146,178,31,...,,3,5,2,7,1,1,4,NaN,0
3,59.166.0.2,21553,149.171.126.2,25,tcp,FIN,0.053948,37812,3380,31,...,,1,1,4,7,1,1,3,NaN,0
4,59.166.0.8,45212,149.171.126.4,53,udp,CON,0.000953,146,178,31,...,,2,5,2,1,1,1,2,NaN,0

In [4]:
data1.shape, data2.shape, data3.shape, data4.shape

((700001, 49), (700001, 49), (700001, 49), (440044, 49))

**from here ...**

In [5]:
Columns = list(feature['Name'])
Columns = [str(col).strip() for col in Columns]
Types = list(feature['Type ']) # whitespace in header, i don't handel it because it's not necessary for this project

### Colceting all data in one DataFrame

In [6]:
DataSet = pd.concat([data1, data2, data3, data4], axis=0, ignore_index=True)
DataSet.columns = Columns

In [7]:
feature['Type '].unique()

array(['nominal', 'integer', 'Float', 'Integer', 'Timestamp', 'Binary',
       'binary'], dtype=object)

- **type mismatch**

### Handeling Binary Columns

In [8]:
display(DataSet['is_ftp_login'].unique())
display(DataSet['is_sm_ips_ports'].unique())
display(DataSet['Label'].unique())

array([ 0.,  1., nan,  2.,  4.])

array([0, 1])

array([0, 1])

- **"is ftp_login" column has values ​​other than 1 and 0**

In [9]:
DataSet['is_ftp_login'] = DataSet['is_ftp_login'].fillna(0)
DataSet['is_ftp_login'] = DataSet['is_ftp_login'].apply(lambda x: 1 if x>0 else 0)

In [10]:
DataSet['is_ftp_login'].unique()

array([0, 1])

### Type Handeling

In [11]:
def clean_and_map_type(t):
    t_str = str(t).strip().lower()
    if 'integer' in t_str or 'binary' in t_str:
        return 'Int64'
    elif 'float' in t_str:
        return 'float64'
    elif 'timestamp' in t_str or 'date' in t_str:
        return 'datetime64[ns]'
    else:
        return 'object'

type_dict = {
    col: clean_and_map_type(t) 
    for col, t in zip(Columns, feature['Type '])
}

for col, target_type in type_dict.items():
    if target_type == 'Int64':
        DataSet[col] = pd.to_numeric(DataSet[col], errors='coerce').astype('Int64')
        
    elif target_type == 'float64':
        DataSet[col] = pd.to_numeric(DataSet[col], errors='coerce')
        
    elif target_type == 'datetime64[ns]':
        DataSet[col] = pd.to_datetime(DataSet[col], errors='coerce')
        
    else:
        DataSet[col] = DataSet[col].astype(str)

DataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2540047 entries, 0 to 2540046
Data columns (total 49 columns):
 #   Column            Dtype
---  ------            -----
 0   srcip             object
 1   sport             Int64
 2   dstip             object
 3   dsport            Int64
 4   proto             object
 5   state             object
 6   dur               float64
 7   sbytes            Int64
 8   dbytes            Int64
 9   sttl              Int64
 10  dttl              Int64
 11  sloss             Int64
 12  dloss             Int64
 13  service           object
 14  Sload             float64
 15  Dload             float64
 16  Spkts             Int64
 17  Dpkts             Int64
 18  swin              Int64
 19  dwin              Int64
 20  stcpb             Int64
 21  dtcpb             Int64
 22  smeansz           Int64
 23  dmeansz           Int64
 24  trans_depth       Int64
 25  res_bdy_len       Int64
 26  Sjit              float64
 27  Djit              float64
 28  Stime             datetime64[ns]
 29  Ltime             datetime64[ns]
 30  Sintpkt           float64
 31  Dintpkt           float64
 32  tcprtt            float64
 33  synack            float64
 34  ackdat            float64
 35  is_sm_ips_ports   Int64
 36  ct_state_ttl      Int64
 37  ct_flw_http_mthd  Int64
 38  is_ftp_login      Int64
 39  ct_ftp_cmd        Int64
 40  ct_srv_src        Int64
 41  ct_srv_dst        Int64
 42  ct_dst_ltm        Int64
 43  ct_src_ ltm       Int64
 44  ct_src_dport_ltm  Int64
 45  ct_dst_sport_ltm  Int64
 46  ct_dst_src_ltm    Int64
 47  attack_cat        object
 48  Label             Int64
dtypes: Int64(31), datetime64[ns](2), float64(10), object(6)
memory usage: 1.0+ GB

In [12]:
DataSet.head()

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,nan,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,nan,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,nan,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,nan,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,nan,0

In [13]:
DataSet.shape

(2540047, 49)

### Handeling Object Columns

In [14]:
for col in DataSet:
    if DataSet[col].dtype == "object":
        display(f"Column: {col}")
        display(DataSet[col].unique())
        print('-' * 50)

'Column: srcip'

array(['59.166.0.0', '59.166.0.6', '59.166.0.5', '59.166.0.3',
       '10.40.182.3', '59.166.0.7', '10.40.170.2', '59.166.0.1',
       '59.166.0.2', '59.166.0.4', '175.45.176.3', '175.45.176.2',
       '175.45.176.0', '59.166.0.8', '59.166.0.9', '175.45.176.1',
       '10.40.182.1', '10.40.85.1', '192.168.241.243', '10.40.85.30',
       '149.171.126.16', '149.171.126.2', '149.171.126.11',
       '149.171.126.4', '149.171.126.5', '149.171.126.17',
       '149.171.126.19', '149.171.126.9', '149.171.126.8',
       '149.171.126.7', '149.171.126.15', '149.171.126.6',
       '149.171.126.0', '149.171.126.1', '149.171.126.3',
       '149.171.126.13', '149.171.126.12', '149.171.126.10',
       '149.171.126.18', '127.0.0.1', '149.171.126.14', '10.40.85.10',
       '10.40.182.6'], dtype=object)

--------------------------------------------------

'Column: dstip'

array(['149.171.126.6', '149.171.126.9', '149.171.126.7', '149.171.126.5',
       '149.171.126.0', '149.171.126.4', '10.40.182.3', '10.40.170.2',
       '149.171.126.18', '149.171.126.16', '149.171.126.8',
       '149.171.126.2', '149.171.126.1', '149.171.126.10',
       '149.171.126.3', '149.171.126.15', '149.171.126.14',
       '149.171.126.12', '149.171.126.13', '149.171.126.11', '224.0.0.5',
       '149.171.126.17', '149.171.126.19', '192.168.241.243',
       '10.40.85.1', '10.40.85.30', '175.45.176.3', '224.0.0.1',
       '59.166.0.4', '175.45.176.0', '59.166.0.9', '59.166.0.6',
       '175.45.176.2', '59.166.0.2', '59.166.0.5', '59.166.0.7',
       '59.166.0.1', '59.166.0.8', '59.166.0.0', '175.45.176.1',
       '59.166.0.3', '32.50.32.66', '10.40.198.10', '127.0.0.1',
       '192.168.241.50', '10.40.182.255', '10.40.182.6'], dtype=object)

--------------------------------------------------

'Column: proto'

array(['udp', 'arp', 'tcp', 'ospf', 'icmp', 'igmp', 'sctp', 'udt', 'sep',
       'sun-nd', 'swipe', 'mobile', 'pim', 'rtp', 'ipnip', 'ip', 'ggp',
       'st2', 'egp', 'cbt', 'emcon', 'nvp', 'igp', 'xnet', 'argus',
       'bbn-rcc', 'chaos', 'pup', 'hmp', 'mux', 'dcn', 'prm', 'trunk-1',
       'xns-idp', 'trunk-2', 'leaf-1', 'leaf-2', 'irtp', 'rdp', 'iso-tp4',
       'netblt', 'mfe-nsp', 'merit-inp', '3pc', 'xtp', 'idpr', 'tp++',
       'ddp', 'idpr-cmtp', 'ipv6', 'il', 'idrp', 'ipv6-frag', 'sdrp',
       'ipv6-route', 'gre', 'rsvp', 'mhrp', 'bna', 'esp', 'i-nlsp',
       'narp', 'ipv6-no', 'tlsp', 'skip', 'ipv6-opts', 'any', 'cftp',
       'sat-expak', 'kryptolan', 'rvd', 'ippc', 'sat-mon', 'ipcv', 'visa',
       'cpnx', 'cphb', 'wsn', 'pvp', 'br-sat-mon', 'wb-mon', 'wb-expak',
       'iso-ip', 'secure-vmtp', 'vmtp', 'vines', 'ttp', 'nsfnet-igp',
       'dgp', 'tcf', 'eigrp', 'sprite-rpc', 'larp', 'mtp', 'ax.25',
       'ipip', 'micp', 'aes-sp3-d', 'encap', 'etherip', 'pri-enc', 'gmtp',
       'pnni', 'ifmp', 'aris', 'qnx', 'a/n', 'scps', 'snp', 'ipcomp',
       'compaq-peer', 'ipx-n-ip', 'vrrp', 'zero', 'pgm', 'iatp', 'ddx',
       'l2tp', 'srp', 'stp', 'smp', 'uti', 'sm', 'ptp', 'fire', 'crtp',
       'isis', 'crudp', 'sccopmce', 'sps', 'pipe', 'iplt', 'unas', 'fc',
       'ib'], dtype=object)

--------------------------------------------------

'Column: state'

array(['CON', 'INT', 'FIN', 'URH', 'REQ', 'ECO', 'RST', 'CLO', 'TXD',
       'URN', 'no', 'ACC', 'PAR', 'MAS', 'TST', 'ECR'], dtype=object)

--------------------------------------------------

'Column: service'

array(['dns', '-', 'http', 'smtp', 'ftp-data', 'ftp', 'ssh', 'pop3',
       'snmp', 'ssl', 'irc', 'radius', 'dhcp'], dtype=object)

--------------------------------------------------

'Column: attack_cat'

array(['nan', 'Exploits', 'Reconnaissance', 'DoS', 'Generic', 'Shellcode',
       ' Fuzzers', 'Worms', 'Backdoors', 'Analysis', ' Reconnaissance ',
       'Backdoor', ' Fuzzers ', ' Shellcode '], dtype=object)

--------------------------------------------------

In [15]:
DataSet['attack_cat'] = DataSet['attack_cat'].astype(str).replace({
    'nan': 'Normal', 
    'Backdoor': 'Backdoors'
}).fillna('Normal')

DataSet['service'] = DataSet['service'].replace('-', 'none')

DataSet = DataSet.drop(columns=['srcip', 'dstip'], errors='ignore')

display(DataSet['attack_cat'].unique())
display(DataSet['service'].unique())

array(['Normal', 'Exploits', 'Reconnaissance', 'DoS', 'Generic',
       'Shellcode', ' Fuzzers', 'Worms', 'Backdoors', 'Analysis',
       ' Reconnaissance ', ' Fuzzers ', ' Shellcode '], dtype=object)

array(['dns', 'none', 'http', 'smtp', 'ftp-data', 'ftp', 'ssh', 'pop3',
       'snmp', 'ssl', 'irc', 'radius', 'dhcp'], dtype=object)

attack_cat: Replaced 'nan' strings/nulls with 'Normal' and standardized 'Backdoor' to 'Backdoors'.

service: Replaced missing service placeholders ('-') with 'none'.

srcip & dstip: Dropped IP address columns to prevent the model from memorizing specific IP targets instead of learning network behaviors.

### Removing Whitespaces

In [16]:
for col in DataSet:
    if DataSet[col].dtype == "object":
        DataSet[col] = DataSet[col].astype(str).str.strip()

### Checking Nulls

In [17]:
null_counts = DataSet.isnull().sum()

null_counts = null_counts[null_counts > 0].sort_values(ascending=False)

for col, count in null_counts.items():
    print(f'{col:<19}: {count}')

ct_ftp_cmd         : 1429879
ct_flw_http_mthd   : 1348145
dsport             : 304
sport              : 8

if wanna do imputing frindo, do it after spliting data

In [18]:
DataSet = DataSet.dropna(how='all', axis=1)
DataSet = DataSet.dropna(how='all', axis=0)

In [19]:
DataSet.shape

(2540047, 47)

### Checking Duplication

In [20]:
DataSet[DataSet.duplicated()]

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
10,0,0,arp,INT,0.000000,46,0,0,0,0,...,0,2,2,2,2,2,2,2,Normal,0
11,0,0,arp,INT,0.000000,46,0,0,0,0,...,0,2,2,2,2,2,2,2,Normal,0
12,0,0,arp,INT,0.000000,46,0,0,0,0,...,0,2,2,2,2,2,2,2,Normal,0
72,15807,53,udp,CON,0.001118,132,164,31,29,0,...,0,12,8,5,3,3,2,2,Normal,0
121,0,0,ospf,INT,50.004337,384,0,1,0,0,...,0,2,4,4,2,2,4,2,Normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2540027,47439,53,udp,INT,0.000001,114,0,254,0,0,...,<NA>,15,15,15,15,15,15,15,Generic,1
2540035,53521,21,tcp,CON,1.086072,1940,2404,31,29,8,...,2,2,2,3,3,2,2,3,Normal,0
2540040,61886,21,tcp,CON,3.108071,1148,1402,31,29,5,...,2,2,2,2,4,2,2,3,Normal,0
2540043,20848,21,tcp,CON,0.365058,456,346,31,29,2,...,2,2,2,2,2,2,2,2,Normal,0
2540044,21511,21,tcp,CON,6.335154,1802,2088,31,29,7,...,2,2,2,4,2,2,2,2,Normal,0

In [21]:
print(DataSet.duplicated().sum())

481056

In [22]:
DataSet = DataSet.drop_duplicates()

In [23]:
DataSet.shape

(2058991, 47)

### Checking Outliers

In [24]:
def FindAndHandelQutlierInData(data, col):
    clean_col = data[col].dropna()
    Q1 = np.quantile(clean_col, .25)
    Q3 = np.quantile(clean_col, .75)
    IQR = Q3 - Q1
    lower = max(0, Q1 - 1.5 * IQR)
    upper = Q3 + 1.5 * IQR

    NoOutlier = ((clean_col > upper) | (clean_col < lower)).sum()
    print(f"{col:<19}: found {NoOutlier:<9} outlier(s) -> bounds = [{lower:.2f}, {upper:.2f}]")

for col in DataSet.columns:
    if DataSet[col].dtype in ['Int64', 'float64']:
        FindAndHandelQutlierInData(DataSet, col)

sport              : found 0         outlier(s) -> bounds = [0.00, 99189.50]
dsport             : found 81093     outlier(s) -> bounds = [0.00, 58895.50]
dur                : found 352869    outlier(s) -> bounds = [0.00, 0.83]
sbytes             : found 227115    outlier(s) -> bounds = [0.00, 8684.00]
dbytes             : found 216397    outlier(s) -> bounds = [0.00, 49339.00]
sttl               : found 172674    outlier(s) -> bounds = [31.00, 31.00]
dttl               : found 173398    outlier(s) -> bounds = [29.00, 29.00]
sloss              : found 195376    outlier(s) -> bounds = [0.00, 17.50]
dloss              : found 104730    outlier(s) -> bounds = [0.00, 37.50]
Sload              : found 190203    outlier(s) -> bounds = [0.00, 2618576.75]
Dload              : found 269705    outlier(s) -> bounds = [0.00, 9475365.29]
Spkts              : found 129574    outlier(s) -> bounds = [0.00, 114.00]
Dpkts              : found 139328    outlier(s) -> bounds = [0.00, 109.00]
swin               : found 0         outlier(s) -> bounds = [0.00, 637.50]
dwin               : found 0         outlier(s) -> bounds = [0.00, 637.50]
stcpb              : found 0         outlier(s) -> bounds = [0.00, 6920937260.00]
dtcpb              : found 0         outlier(s) -> bounds = [0.00, 6917936917.50]
smeansz            : found 170528    outlier(s) -> bounds = [0.00, 227.00]
dmeansz            : found 23680     outlier(s) -> bounds = [0.00, 1291.00]
trans_depth        : found 199017    outlier(s) -> bounds = [0.00, 0.00]
res_bdy_len        : found 181054    outlier(s) -> bounds = [0.00, 0.00]
Sjit               : found 354402    outlier(s) -> bounds = [0.00, 1867.68]
Djit               : found 364677    outlier(s) -> bounds = [0.00, 204.70]
Sintpkt            : found 345549    outlier(s) -> bounds = [0.00, 29.53]
Dintpkt            : found 342894    outlier(s) -> bounds = [0.00, 25.96]
tcprtt             : found 105401    outlier(s) -> bounds = [0.00, 0.00]
synack             : found 104498    outlier(s) -> bounds = [0.00, 0.00]
ackdat             : found 117637    outlier(s) -> bounds = [0.00, 0.00]
is_sm_ips_ports    : found 2423      outlier(s) -> bounds = [0.00, 0.00]
ct_state_ttl       : found 136967    outlier(s) -> bounds = [0.00, 0.00]
ct_flw_http_mthd   : found 199009    outlier(s) -> bounds = [0.00, 0.00]
is_ftp_login       : found 39684     outlier(s) -> bounds = [0.00, 0.00]
ct_ftp_cmd         : found 39771     outlier(s) -> bounds = [0.00, 0.00]
ct_srv_src         : found 88737     outlier(s) -> bounds = [0.00, 14.50]
ct_srv_dst         : found 74009     outlier(s) -> bounds = [0.00, 14.50]
ct_dst_ltm         : found 66019     outlier(s) -> bounds = [0.00, 9.50]
ct_src_ ltm        : found 108254    outlier(s) -> bounds = [0.00, 9.50]
ct_src_dport_ltm   : found 378782    outlier(s) -> bounds = [1.00, 1.00]
ct_dst_sport_ltm   : found 100670    outlier(s) -> bounds = [1.00, 1.00]
ct_dst_src_ltm     : found 91760     outlier(s) -> bounds = [0.00, 6.00]
Label              : found 99643     outlier(s) -> bounds = [0.00, 0.00]

Here is a brief summary of the preprocessing steps and reasons:

* **Fixed Encoding**: Used `latin1` to resolve reading errors and removed byte order mark (BOM) characters (`ï»¿`).
* **Dropped Duplicates**: Removed identical rows to prevent model overfitting and data leakage.
* **Cleaned Anomalous Values**: Converted `is_ftp_login` to a clean binary flag (`0`/`1`), replaced `'-'` in `service` with `'none'`, and merged `'Backdoor'` into `'Backdoors'` in `attack_cat`.
* **Kept Outliers**: Preserved extreme values because high packet/byte rates represent key attack signatures.
* **Dropped IP Addresses**: Removed `srcip` and `dstip` so the model learns attack behaviors rather than memorizing specific network addresses.

In [25]:
DataSet.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2058991 entries, 0 to 2540046
Data columns (total 47 columns):
 #   Column            Dtype
---  ------            -----
 0   sport             Int64
 1   dsport            Int64
 2   proto             object
 3   state             object
 4   dur               float64
 5   sbytes            Int64
 6   dbytes            Int64
 7   sttl              Int64
 8   dttl              Int64
 9   sloss             Int64
 10  dloss             Int64
 11  service           object
 12  Sload             float64
 13  Dload             float64
 14  Spkts             Int64
 15  Dpkts             Int64
 16  swin              Int64
 17  dwin              Int64
 18  stcpb             Int64
 19  dtcpb             Int64
 20  smeansz           Int64
 21  dmeansz           Int64
 22  trans_depth       Int64
 23  res_bdy_len       Int64
 24  Sjit              float64
 25  Djit              float64
 26  Stime             datetime64[ns]
 27  Ltime             datetime64[ns]
 28  Sintpkt           float64
 29  Dintpkt           float64
 30  tcprtt            float64
 31  synack            float64
 32  ackdat            float64
 33  is_sm_ips_ports   Int64
 34  ct_state_ttl      Int64
 35  ct_flw_http_mthd  Int64
 36  is_ftp_login      Int64
 37  ct_ftp_cmd        Int64
 38  ct_srv_src        Int64
 39  ct_srv_dst        Int64
 40  ct_dst_ltm        Int64
 41  ct_src_ ltm       Int64
 42  ct_src_dport_ltm  Int64
 43  ct_dst_sport_ltm  Int64
 44  ct_dst_src_ltm    Int64
 45  attack_cat        object
 46  Label             Int64
dtypes: Int64(31), datetime64[ns](2), float64(10), object(4)
memory usage: 814.9+ MB

In [26]:
DataSet.to_csv('Cleaned_UNSW-NB15.csv', index=False)

## Dataset Overview — UNSW-NB15

The UNSW-NB15 dataset was created by the Cyber Range Lab of the Australian
Centre for Cyber Security (ACCS) using the IXIA PerfectStorm tool to generate
a hybrid of real modern normal network traffic and synthetic contemporary
attack behaviours.

- **Total records used in this project:** ~2.5M raw connections (4 CSV parts
  combined: `UNSW-NB15_1.csv` → `UNSW-NB15_4.csv`)
- **Features:** 49 columns (47 predictive features + 2 target columns)
- **Feature reference:** `NUSW-NB15_features.csv` (name, type, description
  for every column — no headers exist in the raw CSVs, so this file is
  required to reconstruct them)

### Feature groups
| Group | Examples | What it captures |
|---|---|---|
| Flow identifiers | `srcip`, `sport`, `dstip`, `dsport`, `proto` | Connection endpoints & protocol |
| Basic features | `dur`, `sbytes`, `dbytes`, `sttl`, `dttl`, `state` | Duration, byte counts, TTLs, connection state |
| Content features | `service`, `swin`, `dwin`, `stcpb`, `dtcpb`, `smeansz`, `dmeansz` | Payload/header-level details |
| Time features | `Sjit`, `Djit`, `Sintpkt`, `Dintpkt`, `tcprtt`, `synack`, `ackdat` | Jitter and round-trip timing |
| Connection-count (ct_*) features | `ct_srv_src`, `ct_dst_ltm`, `ct_dst_src_ltm`, etc. | Aggregated counts of similar connections in a time window (useful for detecting scans/floods) |
| Targets | `Label`, `attack_cat` | Binary and multiclass ground truth |

### Target variables
- **`Label`** (binary): `0` = Normal traffic, `1` = Attack
- **`attack_cat`** (multiclass): the specific attack family when `Label == 1`
  — Fuzzers, Analysis, Backdoors, DoS, Exploits, Generic, Reconnaissance,
  Shellcode, Worms. Empty/NaN when the record is Normal.

## Data Quality Issues Found & How They Were Handled

| Issue | Where | Fix Applied | Why |
|---|---|---|---|
| No column headers in raw CSVs | All 4 files | Column names/types mapped from `NUSW-NB15_features.csv` | The dataset is split into 4 raw parts without headers |
| Encoding errors | `NUSW-NB15_features.csv` | Read with `ISO-8859-1` / `latin1` | UTF-8 failed on some special characters in feature descriptions |
| Type mismatches | Almost every column | Explicit casting based on the feature file's declared type (`Int64`, `float64`, `datetime64[ns]`, `object`) | Raw CSVs load everything as generic objects; correct dtypes are required for numeric analysis and modeling |
| Dirty binary flag | `is_ftp_login` | Any non-zero/invalid value forced to `1`, missing forced to `0` | Column is supposed to be strictly binary (0/1) but contained inconsistent values |
| Inconsistent categorical labels | `attack_cat` | `NaN` → `'Normal'`, `'Backdoor'` → `'Backdoors'` (typo fix) | NaN only occurs for benign traffic and needs an explicit label for multiclass modeling; `'Backdoor'`/`'Backdoors'` was a spelling inconsistency in the raw data that would otherwise count as two different classes |
| Placeholder value | `service` | `'-'` → `'none'` | `'-'` meant "no service detected", clearer as an explicit category |
| Leaky identifiers | `srcip`, `dstip` | Dropped | Using raw IP addresses lets the model memorize specific known-attacker addresses instead of learning generalizable attack *behavior* — this would fail on any new/unseen network |
| Leading/trailing whitespace | All `object` columns (e.g. `' Fuzzers'` vs `'Fuzzers'`) | Stripped with `.str.strip()` | Would otherwise be silently counted as separate categories |
| Fully-empty rows/columns | Whole dataset | Dropped | No informational value |
| Duplicate records | Whole dataset | Dropped (~exact duplicate rows) | Prevents the model from overweighting repeated connections and reduces train/test leakage risk |
| Outliers (IQR method) | All numeric features | **Kept, not removed** | In network security, extreme values (huge byte counts, unusual durations, packet floods) are often *the actual attack signature* — removing them would strip out the very patterns the model needs to learn |